title: "Docendo Discimus"
author: "Hugo Alberto Levi"
description: "Where I keep some things."
permalink: /:title/
lang: "en"

show_footer: false           # show the "previous" and "next" links at the end of each post
dark_theme: false            # use the dark mode as default
dark_header: false           # keep the header dark
dark_footer: false           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
  - README.md
  - Github: "http://github.com/hugo-levi/hugo-levi.github.io"

#icons:                      # icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:hugo-levi@users.noreply.github.com"
  github: "http://github.com/hugo-levi/hugo-levi.github.io"
#  rss: "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
